services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      # 关键：APP_HOST 必须是 <id>_main_1
      # 你的 id 是 "tao-metube"，所以这里必须是 "tao-metube_main_1"
      APP_HOST: tao-metube_main_1

      # 关键：APP_PORT 必须是 metube 的内部端口 8081
      APP_PORT: 8081

  # 2. MeTube 应用服务
  main:
    image: ghcr.io/alexta69/metube:latest
    
    # 关键：container_name 必须与 APP_HOST 完全一致
    container_name: tao-metube_main_1
    
    # user: '1000:1000'
    restart: unless-stopped
    
    expose:
      - "8081"
      
    volumes:
      # 使用 Umbrel 标准数据路径，自动处理权限
      - ${APP_DATA_DIR}/data:/downloads
