services:
  # 1. Umbrel 反向代理服务
  app_proxy:
    environment:
      # APP_HOST: 参照 memos 格式，必须精确匹配下方 main 服务的 container_name
      # 我们假设 app-id 是 'metube'
      APP_HOST: metube_main_1

      # APP_PORT: 必须是 metube 容器的 *内部* 端口
      APP_PORT: 8081

  # 2. MeTube 应用服务
  main:
    # 使用官方 metube 镜像
    image: ghcr.io/alexta69/metube:latest
    
    # 参照 memos，使用 'main' 作为服务名，并设置 'container_name'
    # 这个名字必须与上面的 APP_HOST 一致
    container_name: metube_main_1
    
    # 参照 memos，使用标准 1000:1000 用户
    user: '1000:1000'
    
    # 使用 metube 官方的重启策略
    restart: unless-stopped
    
    # 参照 memos，移除 'ports'，替换为 'expose'
    expose:
      - "8081" # 声明内部端口
      
    volumes:
      # 参照 memos，使用 ${APP_DATA_DIR} 自动管理数据和权限
      # 将 metube 内部的 /downloads 路径映射到 Umbrel 的标准数据目录
      - ${APP_DATA_DIR}/data:/downloads
