version: '3.7'
services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      # 关键: 主机链 (匹配你的 id: tao-vert)
      APP_HOST: tao-vert_main_1
      
      # 关键: 端口链 (修正)
      # 代理的目标端口 *必须* 是 Vert 的内部端口 80
      APP_PORT: 80

  # 2. Vert 应用服务
  main:
    image: 'ghcr.io/vert-sh/vert:latest'
    
    # 关键: 主机链 (匹配 APP_HOST)
    container_name: tao-vert_main_1
    
    restart: unless-stopped

    # 关键: 端口链 (移除 'ports'，替换为 'expose')
    # 声明容器的内部端口
    expose:
      - "80"
