services:
  app_proxy:
    environment:
      APP_HOST: vert_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: 'false'
    container_name: vert_app_proxy_1

  server:
    image: ghcr.io/vert-sh/vert:latest
    container_name: vert_server_1
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /data:/data          # 挂载整个磁盘
      - /DATA/AppData/vert:/config
    restart: on-failure
