services:
  # 服务名称必须是 "app"
  app:
    image: ghcr.io/vert-sh/vert:latest
    container_name: vert
    restart: unless-stopped
    
    environment:
      # Umbrel 会自动提供 $APP_DOMAIN 变量
      PUB_HOSTNAME: "${APP_DOMAIN}"
      
      # 其他从你原始配置中转换过来的环境变量
      PUB_PLAUSIBLE_URL: "${PUB_PLAUSIBLE_URL:-}"
      PUB_ENV: "production"
      PUB_DISABLE_ALL_EXTERNAL_REQUESTS: "${DISABLE_ALL_EXTERNAL_REQUESTS:-false}"
      PUB_VERTD_URL: "${PUB_VERTD_URL:-}"
      PUB_DONATION_URL: "${PUB_DONATION_URL:-https://donations.vert.sh}"
      PUB_STRIPE_KEY: "${PUB_STRIPE_KEY:-pk_live_51RDVmAGSxPVad6bQwzVNnbc28nlmzA30krLWk1fefCMpUPiSRPkavMMbGqa8A3lUaOCMlsUEVy2CWDYg0ip3aPpL00ZJlsMkf2}"
      
    # 再次强调：这里一定不能有 "ports:"
