services:
  # 定义第一个服务：app_proxy
  app_proxy:
    environment:
      # ... (其他环境变异) ...

      # 定义应用主机名 (使用服务名)
      APP_HOST: server  # <-- 修改 1：确保这里是 server

      # 定义应用内部监听的端口号
      APP_PORT: 80      # <-- 修改 2：从 3100 更改为 80

  # 定义第二个服务：server (你的实际应用)
  server:
    # 指定容器使用的镜像
    image: ghcr.io/vert-sh/vert:latest
    # ... (user, init 等其他配置) ...

    # 移除 'ports' 映射，因为 app_proxy 会处理外部访问
    # ports:
    #   - ${PORT:-3000}:80  <-- 删除或注释掉这一行

    # 使用 'expose' 声明容器的内部端口
    expose:
      - "80"             # <-- 修改 3：添加这一行 (或从 3100 改为 80)
