services:
  vert:
    container_name: vert
    image: ghcr.io/vert-sh/vert:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      PUB_HOSTNAME: localhost:3000
      PUB_ENV: production
      PUB_DONATION_URL: https://donations.vert.sh
      PUB_STRIPE_KEY: pk_live_51RDVmAGSxPVad6bQwzVNnbc28nlmzA30krLWk1fefCMpUPiSRPkavMMbGqa8A3lUaOCMlsUEVy2CWDYg0ip3aPpL00ZJlsMkf2
