services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      # 关键: 主机链 (必须匹配 'main' 服务的 container_name)
      APP_HOST: tao-video-link_main_1
      # 关键: 端口链 (NGINX 默认的内部端口是 80)
      APP_PORT: 80

  # 2. “启动页”服务 (使用 NGINX)
  main:
    image: 'nginx:alpine'
    
    # 关键: 主机链 (匹配 APP_HOST)
    container_name: tao-video-link_main_1
    
    restart: unless-stopped
    
    # 关键: 权限链 (Case 1)
    # NGINX 以非 root 运行，需要 1000:1000 权限来读取 Umbrel 卷
    user: '1000:1000'
    
    # 关键: 路径链
    # 我们将把一个 HTML 文件夹映射到 NGINX 的网页根目录
    volumes:
      - ${APP_DATA_DIR}/html:/usr/share/nginx/html:ro
      
    # 关键: 端口链 (暴露 NGINX 的内部 80 端口)
    expose:
      - "80"
