services:
  app_proxy:
    environment:
      APP_HOST: tao-video_main_1
      APP_PORT: 80
  main:
    image: 'nginx:alpine'
    container_name: tao-video_main_1
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/html:/usr/share/nginx/html:ro
    expose:
      - "80"
