services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      # 关键: 主机链 (必须匹配 main 服务的 container_name)
      APP_HOST: tao-video_main_1
      # 关键: 端口链 (指向一个任意端口，hello-world 不监听)
      APP_PORT: 80

  # 2. “最小化”服务 (使用 hello-world)
  main:
    image: 'hello-world' # 使用绝对能运行的镜像
    
    # 关键: 主机链 (必须匹配 APP_HOST)
    container_name: tao-video_main_1
    
    # 无需 restart, volumes, expose, user
