services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      # 关键: 主机链 (必须匹配你的 id: tao-video)
      APP_HOST: tao-video_main_1
      # 关键: 端口链 (NGINX 默认的内部端口是 80)
      APP_PORT: 80

  # 2. “启动页”服务 (使用 NGINX)
  main:
    image: 'nginx:alpine'
    
    # 关键: 主机链 (匹配 APP_HOST)
    container_name: tao-video_main_1
    
    restart: unless-stopped
    
    # 关键: 权限链 (Case 2 - NGINX 以 root 启动)
    # 省略 user: 字段
    
    # 关键: 路径链
    # 映射 HTML 文件夹到 NGINX 的网页根目录
    volumes:
      - ${APP_DATA_DIR}/html:/usr/share/nginx/html:ro
      
    # 关键: 端口链 (暴露 NGINX 的内部 80 端口)
    expose:
      - "80"
