version: '3.9'
services:
  app_proxy:
    image: getumbrel/umbrel-app-proxy:v1.1.0
    environment:
      APP_HOST: tao-swingmusic_app_1
      APP_PORT: 1970
      PROXY_AUTH_ADD: 'false'
    container_name: tao-swingmusic_app_proxy_1
    restart: on-failure
    volumes:
      - ${APP_PROXY_DATA_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
  app:
    image: >-
      ghcr.io/swingmx/swingmusic:v2.0.9@sha256:f8dcd4e074355de8fe5e8ae256c0af0441715a0eaf0bf2eabaebc65447ea716c
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/music:/music:rw
      - ${UMBREL_ROOT}/home/Downloads:/downloads
    container_name: tao-swingmusic_app_1
