services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      APP_HOST: tao-swingmusic_main_1
      APP_PORT: 1970
      PROXY_AUTH_ADD: 'false'

  # 2. SwingMusic 应用服务
  main:
    image: 'ghcr.io/swingmx/swingmusic:v2.0.9@sha256:f8dcd4e074355de8fe5e8ae256c0af0441715a0eaf0bf2eabaebc654'
    container_name: tao-swingmusic_main_1
    restart: on-failure
    
    # 关键：按照您的建议，使用 user: '0:0' 强制 root 权限
    user: '0:0'
    
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/music:/music:rw
      
      # --- 保持注释，用于最小化测试 ---
      # - ${UMBREL_ROOT}/home/Downloads:/downloads
      - /root/umbrel/app-data/tao-clouddrive2/mounts/阿里网盘/个人文件/无损音乐545首:/clouddrive_music:ro

    expose:
      - "1970"
