version: '3.9'
services:
  app_proxy:
    # 1. 使用 F 计划的、正确的 app_proxy (没有多余内容)
    environment:
      APP_HOST: tao-swingmusic_app_1
      APP_PORT: 1970
      PROXY_AUTH_ADD: 'false'
    container_name: tao-swingmusic_app_proxy_1

  app:
    image: >-
      ghcr.io/swingmx/swingmusic:v2.0.9@sha256:f8dcd4e074355de8fe5e8ae256c0af0441715a0eaf0bf2eabaebc65447ea716c
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      # 2. 使用 F 计划的、正确的 config 和 music 路径
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/music:/music:rw 
      - ${UMBREL_ROOT}/home/Downloads:/downloads
      
      # 3. <<< I 计划的核心 >>>
      # 添加 B 计划的挂载 (我们现在知道这不会导致闪回了)
      # 我们把你的网盘挂载点，映射到容器内的 /clouddrive 目录
      - /DATA/AppData/umbrel/app-data/tao-clouddrive2/mounts:/clouddrive:ro
      
    container_name: tao-swingmusic_app_1
