version: '3.9'
services:
  app_proxy:
    environment:
      APP_HOST: tao-swingmusic_app_1 # <--- 修改点 1
      APP_PORT: 1970
      PROXY_AUTH_ADD: 'false'
    container_name: tao-swingmusic_app_proxy_1 # <--- 修改点 2

  app:
    image: >-
      ghcr.io/swingmx/swingmusic:v2.0.9@sha256:f8dcd4e074355de8fe5e8ae256c0af0441715a0eaf0bf2eabaebc65447ea716c
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      # 我们使用 100% 官方的路径
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/music:/music:rw
      - ${UMBREL_ROOT}/home/Downloads:/downloads
    container_name: tao-swingmusic_app_1 # <--- 修改点 3
