main:
  image: 'owntone/owntone:staging'
  container_name: tao-owntone_main_1
  restart: unless-stopped

  privileged: true
  pid: "host"
  tmpfs:
    - /run
    - /tmp

  volumes:
    - /data/app-data/tao-owntone/config:/etc/owntone
    - /data/app-data/tao-owntone/database:/var/cache/owntone
    - /data/storage/music:/srv/media:ro
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

  environment:
    UID: 1000
    GID: 1000

  expose:
    - "3689"
