services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      APP_HOST: tao-owntone_main_1
      APP_PORT: 3689

  # 2. OwnTone 主服务
  main:
    image: 'owntone/owntone:staging'
    container_name: tao-owntone_main_1
    restart: unless-stopped

    # -------------------------------
    # 关键修正：保留 'privileged' (用于 cgroup 和 mount 权限)
    privileged: true
    
    # 关键修正：移除 'pid: "host"'
    # 'pid: "host"' 会导致容器共享主机的 PID 空间，
    # 使得容器的 init 进程无法成为 PID 1，从而启动失败。
    # -------------------------------

    # tmpfs 挂载 (init 系统需要)
    tmpfs:
      - /run
      - /tmp

    # 卷（已合并）
    volumes:
      # 系统挂载
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      
      # 应用数据卷
      - /data/app-data/tao-owntone/config:/etc/owntone
      - /data/app-data/tao-owntone/database:/var/cache/owntone
      - /data/storage/music:/srv/media:ro

    # 用户 UID/GID
    environment:
      UID: 1000
      GID: 1000

    expose:
      - "3689"
