services:
  # 1. Umbrel 反向代理
  app_proxy:
    image: getumbrel/app-proxy:v1.1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # ✅ 改成短格式
    restart: on-failure
    environment:
      APP_HOST: tao-owntone_main_1
      APP_PORT: 3688

  # 2. Owntone 应用服务
  main:
    image: 'owntone/owntone:latest'
    container_name: tao-owntone_main_1
    restart: unless-stopped
    expose:
      - "3688"
    ports:
      - "3689:3689"
      - "6600:6600"
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/music:/music
    environment:
      - TZ=Asia/Taipei
