  main:
    image: 'owntone/owntone:staging'
    
    container_name: tao-owntone_main_1
    
    restart: unless-stopped

    volumes:
      - /data/app-data/tao-owntone/config:/etc/owntone
      - /data/app-data/tao-owntone/database:/var/cache/owntone
      - /data/storage/music:/srv/media:ro

    environment:
      UID: 1000
      GID: 1000

    expose:
      - "3689"

    # ✅ 自动修复卷权限并启动 OwnTone
    command: >
      sh -c "chown -R 1000:1000 /var/cache/owntone /etc/owntone &&
             exec owntone -f"
