services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      # 关键: 主机链 (匹配你的 id: tao-filebrowser)
      APP_HOST: tao-filebrowser_main_1
      # 关键: 端口链 (必须是 FileBrowser 的 *内部* 端口 80)
      APP_PORT: 80

  # 2. FileBrowser 应用服务
  main:
    image: 'filebrowser/filebrowser:latest'
    
    # 关键: 主机链 (匹配 APP_HOST)
    container_name: tao-filebrowser_main_1
    
    restart: unless-stopped

    # 关键: 路径链 (使用 Umbrel 标准路径，映射到内部 /srv)
    volumes:
      - ${APP_DATA_DIR}/data:/srv
      
    # 关键: 权限链
    # 省略 'user:' 字段，让容器以默认 root 身份运行
    
    # 关键: 端口链 (移除 'ports'，替换为 'expose' 内部 80 端口)
    expose:
      - "80"