services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      # 关键: 主机链 (匹配你的 id: tao-filebrowser)
      APP_HOST: tao-filebrowser_main_1
      # 关键: 端口链 (必须是 FileBrowser 的 *内部* 端口 80)
      APP_PORT: 80

  # 2. FileBrowser 应用服务
  main:
    image: 'filebrowser/filebrowser:latest'
    
    # 关键: 主机链 (匹配 APP_HOST)
    container_name: tao-filebrowser_main_1
    
    restart: unless-stopped

    # 关键: 权限链 (Case 2)
    # 因为你需要管理宿主机的 /data 目录 (归 root 所有),
    # 我们必须移除 user: '1000:1000' 行，让容器以 root 身份运行。
    # user: '1000:1000'  <-- 移除这一行
    
    # 关键: 路径链 (按你的要求修改)
    volumes:
      # /srv 映射到你指定的宿主机 /data 目录
      - /data:/srv
      # 数据库和配置映射到 Umbrel 自己的标准路径
      - ${APP_DATA_DIR}/database:/database
      - ${APP_DATA_DIR}/config:/config
      
    # 关键: 端口链 (移除 'ports'，替换为 'expose' 内部 80 端口)
    expose:
      - "80"
