services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      APP_HOST: tao-firefox_main_1
      APP_PORT: 5800

  # 2. Firefox 应用服务
  main:
    image: 'jlesage/firefox'
    container_name: tao-firefox_main_1
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/config
      
    expose:
      - "5800"

    # 关键: 权限链
    # 省略 'user:' 字段
    
    # ------------------
    # ⬇️ 关键修正 ⬇️
    # ------------------
    # 添加环境变量，强制容器使用中文 (zh_CN.UTF-8) 区域设置
    # 这会告诉容器去加载你放在 /config/fonts 里的中文字体
    environment:
      - LANG=zh_CN.UTF-8
      - LANGUAGE=zh_CN:zh
      - LC_ALL=zh_CN.UTF-8
