services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      APP_HOST: tao-firefox_main_1
      APP_PORT: 5800

  # 2. Firefox 应用服务
  main:
    image: 'jlesage/firefox'
    container_name: tao-firefox_main_1
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/config
      
    expose:
      - "5800"

    # 关键: 权限链
    # 省略 'user:' 字段
    
    # ------------------
    # ⬇️ 关键修正 ⬇️
    # ------------------
    environment:
      # 1. 告诉容器去 *安装* 正确的 Alpine 中文包
      - INSTALL_PACKAGES=font-wqy-zenhei
      
      # 2. 告诉容器去 *使用* 中文 (这些保持不变)
      - LANG=zh_CN.UTF-8
      - LANGUAGE=zh_CN:zh
      - LC_ALL=zh_CN.UTF-8
