services:
  # 定义第一个服务：app_proxy（Umbrel 的反向代理容器，用来连接应用和外部访问）
  app_proxy:
    environment:
      # 环境变量说明：
      # APP_HOST 定义应用主机名，用于 Umbrel 代理内部识别容器地址
      # 格式通常为：<app-id>_<docker-service-name>_1
      APP_HOST: tao-hello-world_server_1
      # APP_PORT 定义应用内部监听的端口号，Umbrel 会将该端口映射出去供访问
      APP_PORT: 3000

  # 定义第二个服务：server（即你的实际应用容器）
  server:
    # 指定容器使用的镜像，这里是 Umbrel 官方示例镜像
    image: getumbrel/community-app-store-hello-world:latest
    # 指定容器运行的用户和用户组 ID（1000:1000 通常是非 root 用户，增强安全性）
    user: "1000:1000"
    # 启用 init 进程，用于正确处理僵尸进程和信号（提高容器稳定性）
    init: true
