services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      APP_HOST: tao-openlist_main_1
      APP_PORT: 5244

  # 2. OpenList 应用服务
  main:
    image: 'openlistteam/openlist:latest'
    container_name: tao-openlist_main_1
    
    # 关键：添加这一行！
    # 这将强制容器以 root (0:0) 身份运行，
    # 从而获得对 root 拥有的数据卷的写入权限。
    user: '0:0'
    
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/opt/openlist/data
      
    environment:
      - UMASK=022
