services:
  # 1. 定义 Umbrel 反向代理服务 (app_proxy)
  # 这个服务充当网关，负责将来自 Umbrel 仪表盘的访问请求
  # 转发到实际的 OpenList 应用程序（即下面的 main 服务）。
  app_proxy:
    environment:
      # APP_HOST: 告诉反向代理，OpenList 主机（main 服务）的容器名称是什么。
      APP_HOST: tao-openlist_main_1
      # APP_PORT: 告诉反向代理，OpenList 主机（main 服务）正在监听的端口号。
      APP_PORT: 5244

  # 2. 定义 OpenList 应用程序主服务 (main)
  # 这是 OpenList 应用程序本身运行的容器。
  main:
    # 指定要使用的 Docker 镜像和版本。
    image: 'openlistteam/openlist:latest'
    # 为这个容器指定一个固定的名称，以便 app_proxy 服务可以通过这个名字找到它。
    container_name: tao-openlist_main_1
    
    # 关键配置：指定容器以 root 用户 (user: '0:0') 运行。
    # 这是为了确保容器拥有足够的权限，
    # 可以向宿主机上由 root 拥有的数据卷（volumes）进行写入操作，
    # 避免因权限不足导致的数据写入失败。
    user: '0:0'
    
    # 重启策略：除非被手动停止，否则容器总是在退出时自动重启。
    restart: unless-stopped
    volumes:
      # 数据卷挂载：将宿主机上的数据目录（路径由 $APP_DATA_DIR 变量提供）
      # 映射到容器内部的 /opt/openlist/data 目录，用于持久化保存 OpenList 的数据。
      - ${APP_DATA_DIR}/data:/opt/openlist/data
      
    environment:
      # 设置文件模式的掩码 (umask)，022 是一个常见的设置，
      # 确保新创建的目录权限为 755 (rwxr-xr-x)，
      # 新创建的文件权限为 644 (rw-r--r--)。
      - UMASK=022
