version: "3.7"

services:
  app_proxy:
    image: getumbrel/umbrel-app-proxy:latest
    environment:
      APP_HOST: tao-nginx_app_1
      APP_PORT: 80
    restart: on-failure
    networks:
      - default

  app:
    image: nginx:latest
    container_name: tao-nginx
    restart: unless-stopped
    volumes:
      - ./data/html:/usr/share/nginx/html
    networks:
      - default

networks:
  default:
    external:
      name: umbrel_main_network
