services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      # 关键: 主机链 (匹配你的 id: tao-clouddrive2)
      APP_HOST: tao-clouddrive2_main_1
      # 关键: 端口链 (匹配 clouddrive2 内部端口)
      APP_PORT: 19798

  # 2. Clouddrive2 应用服务
  main:
    image: 'cloudnas/clouddrive2'
    
    # 关键: 主机链 (匹配 APP_HOST)
    container_name: tao-clouddrive2_main_1
    
    restart: unless-stopped

    # 关键: 权限链
    # 必须省略 'user:' 字段，让它以 root 运行
    # 必须保留 'privileged' 和 'devices' 才能使用 FUSE
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse

    # 关键: 路径链
    volumes:
      # 内部 /Config 映射到 Umbrel 标准数据路径
      - ${APP_DATA_DIR}/data:/Config
      # 内部 /CloudNAS 映射到 Umbrel 的一个新路径
      # 我们添加 :shared 来允许挂载传播
      - ${APP_DATA_DIR}/mounts:/CloudNAS:shared

    # 保留官方的环境变量
    environment:
      - TZ=Asia/Shanghai
      - CLOUDDRIVE_HOME=/Config

    # 关键: 端口链 (移除 'ports'，替换为 'expose')
    expose:
      - "19798"

    # 关键: 移除 network_mode: "host" 和 pid: "host"
    # 否则 app_proxy 无法工作