version: '3.7'
services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      APP_HOST: tao-beszel-agent_main_1
      APP_PORT: 45876

  # 2. Beszel Agent 应用服务
  main:
    image: 'henrygd/beszel-agent'
    container_name: tao-beszel-agent_main_1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_DATA_DIR}/data:/var/lib/beszel-agent
      
    expose:
      - "45876"

    # 关键: 修正所有环境变量，移除所有引号
    environment:
      - LISTEN=45876
      
      # 修正: 移除所有引号，YAML 会自动处理带空格的字符串
      - KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuQFLg1PH63cmv2IMIaA2mmGlojm8s+IkB/p/E4jRPO
      
      - TOKEN=15c7-f9b3fc8fce-4199-621388ce8c
      - HUB_URL=http://192.168.31.16:8090
