# 移除 'version:' 字段
# 移除顶层 'networks:' 字段

services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      APP_HOST: tao-blinko_main_1
      APP_PORT: 1111

  # 2. Blinko 应用服务
  main:
    image: 'blinkospace/blinko:1.6.3'
    container_name: tao-blinko_main_1
    
    # Blinko 需要 user: 1000 (Case 1)
    user: '1000:1000'
    
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=my_ultra_secure_nextauth_secret
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
    expose:
      - "1111"
    volumes:
      - ${APP_DATA_DIR}/data:/app/.blinko
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://main:1111/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
      
  # 3. Postgres 数据库服务
  postgres:
    image: 'postgres:14'
    container_name: tao-blinko_postgres_1
    
    # ------------------
    # ⬇️ 关键修正 (权限) ⬇️
    # ------------------
    # 移除 user: '1000:1000'，让 Postgres 以默认用户 (root) 启动
    # 它会自己管理内部权限 (Case 2)
    # user: '1000:1000' # <-- 移除这一行
    
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - TZ=Asia/Shanghai
    volumes:
      - ${APP_DATA_DIR}/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
