# 移除 'version:' 字段
# 移除顶层 'networks:' 字段

services:
  # 1. Umbrel 反向代理
  app_proxy:
    environment:
      # 关键: 主机链 (匹配你的 id: tao-blinko)
      APP_HOST: tao-blinko_main_1
      # 关键: 端口链 (匹配 Blinko 内部端口)
      APP_PORT: 1111

  # 2. Blinko 应用服务 (原 'blinko-website')
  main:
    # ------------------
    # ⬇️ 关键修正 (镜像名称 v2) ⬇️
    # ------------------
    # 使用你截图中的正确官方镜像名称
    image: 'blinkospace/blinko:latest' # <-- 已修正
    
    # 关键: 主机链 (匹配 APP_HOST)
    container_name: tao-blinko_main_1
    
    # 关键: 权限链 (Case 1)
    user: '1000:1000'
    
    restart: always
    
    depends_on:
      postgres:
        condition: service_healthy
        
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=my_ultra_secure_nextauth_secret
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres
      
    expose:
      - "1111"
      
    volumes:
      - ${APP_DATA_DIR}/data:/app/.blinko
      
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        
    # 关键修正: 将 healthcheck 指向正确的服务名 'main'
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://main:1111/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
      
  # 3. Postgres 数据库服务
  postgres:
    image: 'postgres:14'
    container_name: tao-blinko_postgres_1
    user: '1000:1000'
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - TZ=Asia/Shanghai
    volumes:
      - ${APP_DATA_DIR}/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

